import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import * as THREE from 'three'
import { Scene } from 'three'

export default function Home() {
  const scene = new THREE.Scene();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-3xl font-bold underline flex items-center justify-center h-screen">
        Test
      </main>
    </div>
  )
}
